Write-Host "Nikita Codex Ready"
Write-Host ""
Write-Host "Fast entrypoints:"
Write-Host " - .\\resume.ps1              -> print a ready resume prompt for the current project"
Write-Host " - .\\new-project.ps1 <name>  -> scaffold a new project-local repo next to this pack"
Write-Host " - .\\doctor.ps1              -> check tooling, env, and minimal project context"
Write-Host ""
Write-Host "Human entrypoint: README.md"
Write-Host "Agent entrypoint: AGENTS.md"
Write-Host "Structural check: powershell -ExecutionPolicy Bypass -File scripts\\validate-context-pack.ps1"
